Repository industrieco/battleships-ui, pull requests merged in 2018-03, with the labels that each got.

#1 [documentation, Day-4] added config and readme
  .gitignore
  CONTRIBUTING.md
  README.md
Labels: documentation

#4 [Documentation, Day 4] Added CircleCI Badges
  README.md
Labels: documentation

#5 [Bug Fix, Day-4] changed codecov script name
  package.json
Labels: bug

#7 Add react-web3 dependency
  package-lock.json
  package.json
  src/index.js
Labels: enhancement
